# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define orbs to include in the configuration.
orbs:
  codecov: codecov/codecov@4.0.1

# Define a job to build and test your application.
jobs:
  build-and-test:
    docker:
      # Use the specified OpenJDK image.
      - image: cimg/openjdk:17.0

    steps:
      # Checkout the code as the first step.
      - checkout

      # Build the project using Maven
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      # Run tests
      - run:
          name: Test
          command: mvn test

  # Job to upload coverage reports to Codecov.
  upload-codecov:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      # Checkout the code (optional since it may already be checked out in previous job).
      - checkout

      # Upload the coverage reports to Codecov
      - codecov/upload:
          file: "target/site/jacoco/jacoco.xml" # Adjust the file path if necessary.
          flags: "unit" # Add any flags you want.
          name: "Codecov Upload" # Name for the upload process.

# Define workflows to orchestrate jobs.
workflows:
  version: 2
  build-and-upload:
    jobs:
      - build-and-test  # Run the build-and-test job first.
      - upload-codecov:  # Run the upload-codecov job.
          requires:
            - build-and-test  # Ensure this runs after the build-and-test job.
