# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

# Define a job to be invoked later in a workflow.
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report  # Assuming you're using Jacoco for code coverage
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml  # Specify the path to the coverage report

# Orchestrate jobs using workflows
workflows:
  sample:
    jobs:
      - build-and-test